Repository infinum/eightshift-frontend-libs, pull requests merged in 2020-12, with the labels that each got.

#191 Add relative helpers for line height and em calculation
  styles/scss/functions/_all.scss
  styles/scss/functions/_em.scss
  styles/scss/functions/_line-height.scss
Labels: Scss, improvement

#192 Add a tag to the component
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php
  blocks/init/src/Blocks/components/layout-three-columns/manifest.json
Labels: improvement

#193 Rename BEM selector functions
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/button/components/button-editor.js
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/card/components/card-editor.js
  blocks/init/src/Blocks/components/copyright/components/copyright-editor.js
  blocks/init/src/Blocks/components/copyright/copyright.php
  blocks/init/src/Blocks/components/drawer/components/drawer-editor.js
  blocks/init/src/Blocks/components/drawer/drawer.php
  blocks/init/src/Blocks/components/hamburger/components/hamburger-editor.js
  blocks/init/src/Blocks/components/hamburger/hamburger.php
  blocks/init/src/Blocks/components/heading/components/heading-editor.js
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/layout-three-columns/components/layout-three-columns-editor.js
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php
  blocks/init/src/Blocks/components/link/components/link-editor.js
  blocks/init/src/Blocks/components/link/link.php
  blocks/init/src/Blocks/components/lists/components/lists-editor.js
  blocks/init/src/Blocks/components/lists/lists.php
  blocks/init/src/Blocks/components/loader/components/loader-editor.js
  blocks/init/src/Blocks/components/loader/loader.php
  blocks/init/src/Blocks/components/logo/components/logo-editor.js
  blocks/init/src/Blocks/components/logo/logo.php
  blocks/init/src/Blocks/components/page-overlay/components/page-overlay-editor.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/components/paragraph/paragraph.php
  blocks/init/src/Blocks/components/scroll-to-top/components/scroll-to-top-editor.js
  blocks/init/src/Blocks/components/scroll-to-top/scroll-to-top.php
  blocks/init/src/Blocks/components/search-bar/components/search-bar-editor.js
  blocks/init/src/Blocks/components/search-bar/search-bar.php
  blocks/init/src/Blocks/components/social-links/components/social-links-editor.js
  blocks/init/src/Blocks/components/social-links/social-links.php
  blocks/init/src/Blocks/components/video-button/components/video-button-editor.js
  blocks/init/src/Blocks/components/video-button/video-button.php
  blocks/init/src/Blocks/components/video/components/video-editor.js
  blocks/init/src/Blocks/components/video/video.php
  scripts/helpers/index.js
  scripts/helpers/selector.js
Labels: improvement

#172 Add link reset placeholder
  styles/scss/placeholders/_all.scss
  styles/scss/placeholders/_link.scss
Labels: improvement

#196 Fix attribute type
  blocks/init/src/Blocks/components/heading/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/columns/manifest.json
  blocks/init/src/Blocks/wrapper/manifest.json
Labels: bug

#201 Create _strip-unit.scss
  styles/scss/functions/_all.scss
  styles/scss/functions/_strip-unit.scss
Labels: improvement

#202 Fix relative units
  styles/scss/functions/_em.scss
  styles/scss/functions/_line-height.scss
Labels: improvement

#204 Accordion component update
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/accordion/assets/accordion.js
  scripts/helpers/element-children-height.js
  scripts/helpers/index.js
Labels: improvement

#203 Fix editor component for the Example block
  blocks/init/src/Blocks/custom/example/components/example-editor.js
Labels: improvement

#208 Feature/featured posts
  blocks/init/src/Blocks/custom/featured-categories-posts/components/featured-categories-posts-editor.js
  blocks/init/src/Blocks/custom/featured-categories-posts/components/featured-categories-posts-options.js
  blocks/init/src/Blocks/custom/featured-categories-posts/docs/readme.md
  blocks/init/src/Blocks/custom/featured-categories-posts/docs/story.js
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts-block.js
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts-style.scss
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts.php
  blocks/init/src/Blocks/custom/featured-categories-posts/manifest.json
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-editor.js
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-options.js
  blocks/init/src/Blocks/custom/featured-categories/docs/readme.md
  blocks/init/src/Blocks/custom/featured-categories/docs/story.js
  blocks/init/src/Blocks/custom/featured-categories/featured-categories-block.js
  blocks/init/src/Blocks/custom/featured-categories/featured-categories-style.scss
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-categories/manifest.json
  blocks/init/src/Blocks/custom/featured-posts/components/featured-posts-editor.js
  blocks/init/src/Blocks/custom/featured-posts/components/featured-posts-options.js
  blocks/init/src/Blocks/custom/featured-posts/docs/readme.md
  blocks/init/src/Blocks/custom/featured-posts/docs/story.js
  blocks/init/src/Blocks/custom/featured-posts/featured-posts-block.js
  blocks/init/src/Blocks/custom/featured-posts/featured-posts-style.scss
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/featured-posts/manifest.json
Labels: improvement

#206 Feature/carousel
  blocks/init/src/Blocks/custom/carousel/assets/carousel-slider.js
  blocks/init/src/Blocks/custom/carousel/assets/index.js
  blocks/init/src/Blocks/custom/carousel/carousel-block.js
  blocks/init/src/Blocks/custom/carousel/carousel-editor.scss
  blocks/init/src/Blocks/custom/carousel/carousel-style.scss
  blocks/init/src/Blocks/custom/carousel/carousel.php
  blocks/init/src/Blocks/custom/carousel/components/carousel-editor.js
  blocks/init/src/Blocks/custom/carousel/components/carousel-options.js
  blocks/init/src/Blocks/custom/carousel/docs/readme.md
  blocks/init/src/Blocks/custom/carousel/docs/story.js
  blocks/init/src/Blocks/custom/carousel/manifest.json
  blocks/init/src/Blocks/wrapper/components/wrapper-editor.js
  blocks/init/src/Blocks/wrapper/wrapper.php
Labels: New Block, improvement

#207 Replace bloginfo() with get_bloginfo()
  blocks/init/src/Blocks/components/head/head.php
Labels: improvement

#209 Feature/updating readmes
  blocks/init/src/Blocks/components/accordion/docs/readme.md
  blocks/init/src/Blocks/components/button/docs/readme.md
  blocks/init/src/Blocks/components/card/docs/readme.md
  blocks/init/src/Blocks/components/copyright/docs/readme.md
  blocks/init/src/Blocks/components/drawer/docs/readme.md
  blocks/init/src/Blocks/components/footer/docs/readme.md
  blocks/init/src/Blocks/components/hamburger/docs/readme.md
  blocks/init/src/Blocks/components/head/docs/readme.md
  blocks/init/src/Blocks/components/header/docs/readme.md
  blocks/init/src/Blocks/components/heading/docs/readme.md
  blocks/init/src/Blocks/components/image/docs/readme.md
  blocks/init/src/Blocks/components/layout-three-columns/docs/readme.md
  blocks/init/src/Blocks/components/link/docs/readme.md
  blocks/init/src/Blocks/components/lists/docs/readme.md
  blocks/init/src/Blocks/components/loader/docs/readme.md
  blocks/init/src/Blocks/components/logo/docs/readme.md
  blocks/init/src/Blocks/components/menu/docs/readme.md
  blocks/init/src/Blocks/components/page-overlay/docs/readme.md
  blocks/init/src/Blocks/components/paragraph/docs/readme.md
  blocks/init/src/Blocks/components/scroll-to-top/docs/readme.md
  blocks/init/src/Blocks/components/search-bar/docs/readme.md
  blocks/init/src/Blocks/components/social-links/docs/readme.md
  blocks/init/src/Blocks/components/tracking-before-body-end/docs/readme.md
  blocks/init/src/Blocks/components/tracking-head/docs/readme.md
  blocks/init/src/Blocks/components/video-button/docs/readme.md
  blocks/init/src/Blocks/components/video/docs/readme.md
  blocks/init/src/Blocks/custom/accordion/docs/readme.md
  blocks/init/src/Blocks/custom/button/docs/readme.md
  blocks/init/src/Blocks/custom/card/docs/readme.md
  blocks/init/src/Blocks/custom/carousel/docs/readme.md
  blocks/init/src/Blocks/custom/column/components/column-options.js
  blocks/init/src/Blocks/custom/column/docs/readme.md
  blocks/init/src/Blocks/custom/columns/components/columns-options.js
  blocks/init/src/Blocks/custom/columns/docs/readme.md
  blocks/init/src/Blocks/custom/example/docs/readme.md
  blocks/init/src/Blocks/custom/featured-categories-posts/docs/readme.md
  blocks/init/src/Blocks/custom/featured-categories/docs/readme.md
  blocks/init/src/Blocks/custom/featured-posts/docs/readme.md
  blocks/init/src/Blocks/custom/group/docs/readme.md
  blocks/init/src/Blocks/custom/heading/docs/readme.md
  blocks/init/src/Blocks/custom/image/docs/readme.md
  blocks/init/src/Blocks/custom/link/docs/readme.md
  blocks/init/src/Blocks/custom/lists/docs/readme.md
  blocks/init/src/Blocks/custom/paragraph/docs/readme.md
  blocks/init/src/Blocks/custom/video/docs/readme.md
  blocks/init/src/Blocks/wrapper/components/wrapper-options.js
  blocks/init/src/Blocks/wrapper/docs/readme.md
  scripts/components/help-modal/help-modal.js
Labels: improvement

#211 adding misc fixes
  styles/override-editor.scss
Labels: bug, improvement

#210 Add share component
  blocks/init/src/Blocks/components/share/assets/index.js
  blocks/init/src/Blocks/components/share/assets/share.js
  blocks/init/src/Blocks/components/share/components/share-editor.js
  blocks/init/src/Blocks/components/share/docs/readme.md
  blocks/init/src/Blocks/components/share/docs/story.js
  blocks/init/src/Blocks/components/share/manifest.json
  blocks/init/src/Blocks/components/share/share-style.scss
  blocks/init/src/Blocks/components/share/share.php
Labels: New Component

#215 updating components
  blocks/init/src/Blocks/components/card/docs/story.js
  blocks/init/src/Blocks/components/card/manifest.json
  blocks/init/src/Blocks/custom/accordion/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/columns/manifest.json
  blocks/init/src/Blocks/custom/example/components/example-editor.js
  blocks/init/src/Blocks/custom/example/example.php
  scripts/editor/register-blocks.js
Labels: improvement

#217 updating libs to GB 5.6, fixing variations in editor and storybook,…
  blocks/init/src/Blocks/variations/button-block/docs/readme.md
  blocks/init/src/Blocks/variations/card-simple/docs/readme.md
  blocks/init/src/Blocks/variations/card-simple/docs/story.js
  blocks/init/src/Blocks/variations/card-simple/manifest.json
  package-lock.json
  package.json
  scripts/editor/register-blocks.js
  scripts/storybook/helpers.js
Labels: bug, improvement
