Repository infinum/eightshift-frontend-libs, pull requests merged in 2020-05, with the labels that each got.

#117 Fixing boilerplate setup
  CHANGELOG.md
  blocks/init/src/blocks/custom/example/components/example-editor.js
  blocks/init/src/blocks/custom/example/components/example-options.js
  setup/create-wp-project/package.json
  setup/create-wp-project/src/basics/console.js
  setup/create-wp-project/src/commands/plugin.js
  setup/create-wp-project/src/commands/theme.js
  setup/create-wp-project/src/search-replace.js
  setup/create-wp-project/src/storybook.js
Labels: bug

#122 Feature/transforms
  CHANGELOG.md
  blocks/init/src/blocks/assets/scripts/application-blocks-editor.js
  blocks/init/src/blocks/components/paragraph/paragraph.php
  blocks/init/src/blocks/custom/heading/transforms.js
  blocks/init/src/blocks/custom/paragraph/transforms.js
  scripts/editor/get-block-edit-component.js
  scripts/editor/index.js
  scripts/editor/register-blocks.js
Labels: improvement

#127 Feature/helpers
  blocks/init/src/blocks/custom/button/manifest.json
  blocks/init/src/blocks/custom/card-list/manifest.json
  blocks/init/src/blocks/custom/heading/manifest.json
  blocks/init/src/blocks/custom/link/manifest.json
  blocks/init/src/blocks/custom/lists-info/manifest.json
  blocks/init/src/blocks/custom/lists/manifest.json
  blocks/init/src/blocks/custom/paragraph/manifest.json
  scripts/editor/get-actions.js
Labels: improvement

#123 adding option to have multiple mocked examples in storybook inside in…
  blocks/init/src/blocks/custom/carousel-image/docs/story.js
  blocks/init/src/blocks/custom/carousel-image/manifest.json
  blocks/init/src/blocks/custom/carousel/docs/story.js
  scripts/editor/register-block.js
  scripts/storybook/helpers.js
Labels: improvement

#119 font-face mixin
  CHANGELOG.md
  styles/scss/mixins/_all.scss
  styles/scss/mixins/_font-face.scss
Labels: Scss

#118 Featured Posts block
  CHANGELOG.md
  blocks/init/src/blocks/custom/featured-posts/components/featured-posts-editor.js
  blocks/init/src/blocks/custom/featured-posts/components/featured-posts-options.js
  blocks/init/src/blocks/custom/featured-posts/docs/readme.md
  blocks/init/src/blocks/custom/featured-posts/docs/story.js
  blocks/init/src/blocks/custom/featured-posts/featured-posts-block.js
  blocks/init/src/blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/blocks/custom/featured-posts/manifest.json
Labels: New Block, New Component

#129 adding changes to jumbotron and card-list for alight
  blocks/init/src/blocks/components/image/components/image-editor.js
  blocks/init/src/blocks/components/image/components/image-toolbar.js
  blocks/init/src/blocks/components/image/docs/story.js
  blocks/init/src/blocks/components/video/components/video-editor.js
  blocks/init/src/blocks/components/video/components/video-toolbar.js
  blocks/init/src/blocks/components/video/docs/story.js
  blocks/init/src/blocks/custom/card-list/card-list-block.js
  blocks/init/src/blocks/custom/card-list/components/card-list-options.js
  blocks/init/src/blocks/custom/card-list/components/card-list-toolbar.js
  blocks/init/src/blocks/custom/card/card-block.js
  blocks/init/src/blocks/custom/card/components/card-toolbar.js
  blocks/init/src/blocks/custom/carousel-image/carousel-image-block.js
  blocks/init/src/blocks/custom/carousel-image/components/carousel-image-toolbar.js
  blocks/init/src/blocks/custom/image/components/image-toolbar.js
  blocks/init/src/blocks/custom/image/image-block.js
  blocks/init/src/blocks/custom/jumbotron/components/jumbotron-options.js
  blocks/init/src/blocks/custom/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/blocks/custom/jumbotron/jumbotron-block.js
  blocks/init/src/blocks/custom/video/components/video-toolbar.js
  blocks/init/src/blocks/custom/video/video-block.js
Labels: improvement

#131 Implement ability to toggle wrapper
  blocks/init/src/blocks/wrapper/components/wrapper-editor.js
  blocks/init/src/blocks/wrapper/components/wrapper-options.js
  blocks/init/src/blocks/wrapper/wrapper.js
Labels: improvement

#141 Feature/columns
  .eslintrc
  .storybook/preview-head.html
  blocks/init/src/blocks/components/video/components/video-editor.js
  blocks/init/src/blocks/custom/button/manifest.json
  blocks/init/src/blocks/custom/card-list/manifest.json
  blocks/init/src/blocks/custom/card/manifest.json
  blocks/init/src/blocks/custom/cards-grid/cards-grid-block.js
  blocks/init/src/blocks/custom/cards-grid/cards-grid-editor.scss
  blocks/init/src/blocks/custom/cards-grid/cards-grid-style.scss
  blocks/init/src/blocks/custom/cards-grid/cards-grid.php
  blocks/init/src/blocks/custom/cards-grid/components/cards-grid-editor.js
  blocks/init/src/blocks/custom/cards-grid/docs/readme.md
  blocks/init/src/blocks/custom/cards-grid/docs/story.js
  blocks/init/src/blocks/custom/cards-grid/manifest.json
  blocks/init/src/blocks/custom/cards-list/cards-list-block.js
  blocks/init/src/blocks/custom/cards-list/cards-list-style.scss
  blocks/init/src/blocks/custom/cards-list/cards-list.php
  blocks/init/src/blocks/custom/cards-list/components/cards-list-editor.js
  blocks/init/src/blocks/custom/cards-list/docs/readme.md
  blocks/init/src/blocks/custom/cards-list/docs/story.js
  blocks/init/src/blocks/custom/cards-list/manifest.json
  blocks/init/src/blocks/custom/carousel-image/manifest.json
  blocks/init/src/blocks/custom/carousel-image/transforms.js
  blocks/init/src/blocks/custom/carousel/manifest.json
  blocks/init/src/blocks/custom/column/components/column-responsive-tab-content.js
  blocks/init/src/blocks/custom/column/hooks/index.js
  blocks/init/src/blocks/custom/column/manifest.json
  blocks/init/src/blocks/custom/columns/columns.php
  blocks/init/src/blocks/custom/columns/components/columns-editor.js
  blocks/init/src/blocks/custom/columns/components/columns-options.js
  blocks/init/src/blocks/custom/columns/components/columns-responsive-tab-content.js
  blocks/init/src/blocks/custom/columns/manifest.json
  blocks/init/src/blocks/custom/columns/styles/_shared.scss
  blocks/init/src/blocks/custom/divider/manifest.json
  blocks/init/src/blocks/custom/example/manifest.json
  blocks/init/src/blocks/custom/featured-posts/manifest.json
  blocks/init/src/blocks/custom/group/manifest.json
  blocks/init/src/blocks/custom/heading/manifest.json
  blocks/init/src/blocks/custom/image/manifest.json
  blocks/init/src/blocks/custom/image/transforms.js
  blocks/init/src/blocks/custom/jumbotron/manifest.json
  blocks/init/src/blocks/custom/link/manifest.json
  blocks/init/src/blocks/custom/lists-info/manifest.json
  blocks/init/src/blocks/custom/lists/manifest.json
  blocks/init/src/blocks/custom/paragraph/manifest.json
  blocks/init/src/blocks/custom/quote/manifest.json
  blocks/init/src/blocks/custom/video/manifest.json
  blocks/init/src/blocks/wrapper/components/wrapper-editor.js
  blocks/init/src/blocks/wrapper/components/wrapper-options.js
  blocks/init/src/blocks/wrapper/components/wrapper-responsive-tab-content-simple.js
  blocks/init/src/blocks/wrapper/components/wrapper-responsive-tab-content.js
  blocks/init/src/blocks/wrapper/docs/story.js
  blocks/init/src/blocks/wrapper/manifest.json
  blocks/init/src/blocks/wrapper/wrapper.php
  blocks/init/storybook/preview-head.html
  package-lock.json
  package.json
  scripts/editor/register-block.js
  scripts/storybook/helpers.js
  scripts/storybook/parts.js
Labels: New Block, New Component, improvement

#142 Add GH action for linitng
  .github/workflows/ci.yml
  .travis.yml
Labels: improvement

#145 added fix for colorPalette
  blocks/init/src/blocks/custom/carousel-image/transforms.js
  blocks/init/src/blocks/custom/columns/columns.php
  blocks/init/src/blocks/custom/example/example.php
  blocks/init/src/blocks/custom/image/transforms.js
  scripts/components/color-palette-custom/color-palette-custom.js
Labels: bug

#149 Wrapper and group options
  blocks/init/src/blocks/custom/group/group-block.js
  blocks/init/src/blocks/custom/group/hooks/index.js
  blocks/init/src/blocks/wrapper/components/wrapper-options.js
  blocks/init/src/blocks/wrapper/manifest.json
Labels: improvement

#151 adding additional check for components
  blocks/init/src/blocks/components/button/button.php
  blocks/init/src/blocks/components/heading/heading.php
  blocks/init/src/blocks/components/image/image.php
  blocks/init/src/blocks/components/link/link.php
  blocks/init/src/blocks/components/lists/lists.php
  blocks/init/src/blocks/components/paragraph/paragraph.php
  blocks/init/src/blocks/components/video/video.php
Labels: improvement

#154 Feature/storybook
  CHANGELOG.md
  blocks/init/src/blocks/assets/scripts/application-blocks-editor.js
  blocks/init/src/blocks/custom/button/button-transforms.js
  blocks/init/src/blocks/custom/button/button-variations.js
  blocks/init/src/blocks/custom/carousel-image/carousel-image-block.js
  blocks/init/src/blocks/custom/carousel-image/carousel-image-hooks.js
  blocks/init/src/blocks/custom/carousel-image/carousel-image-transforms.js
  blocks/init/src/blocks/custom/carousel-image/docs/story.js
  blocks/init/src/blocks/custom/carousel-image/hooks/index.js
  blocks/init/src/blocks/custom/carousel-image/manifest.json
  blocks/init/src/blocks/custom/carousel/docs/story.js
  blocks/init/src/blocks/custom/carousel/manifest.json
  blocks/init/src/blocks/custom/column/column-block.js
  blocks/init/src/blocks/custom/column/column-hooks.js
  blocks/init/src/blocks/custom/column/column-icons.js
  blocks/init/src/blocks/custom/column/docs/story.js
  blocks/init/src/blocks/custom/column/manifest.json
  blocks/init/src/blocks/custom/columns/columns-editor.scss
  blocks/init/src/blocks/custom/columns/columns-icons.js
  blocks/init/src/blocks/custom/columns/components/columns-editor.js
  blocks/init/src/blocks/custom/columns/manifest.json
  blocks/init/src/blocks/custom/group/docs/story.js
  blocks/init/src/blocks/custom/group/group-block.js
  blocks/init/src/blocks/custom/group/group-hooks.js
  blocks/init/src/blocks/custom/group/manifest.json
  blocks/init/src/blocks/custom/heading/heading-transforms.js
  blocks/init/src/blocks/custom/image/image-transforms.js
  blocks/init/src/blocks/custom/link/link-transforms.js
  blocks/init/src/blocks/custom/paragraph/paragraph-transforms.js
  blocks/init/src/blocks/manifest.json
  blocks/init/src/blocks/wrapper/hooks/index.js
  blocks/init/src/blocks/wrapper/wrapper-hooks.js
  blocks/init/src/blocks/wrapper/wrapper.js
  package.json
  scripts/editor/index.js
  scripts/editor/register-block.js
  scripts/editor/register-blocks.js
  scripts/editor/with-wrapper.js
  scripts/storybook/helpers.js
  scripts/storybook/index.js
  styles/override-editor.scss
Labels: New Block, New Component, bug, improvement
