Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-07, with the labels that each got.

#378 updating get attributes method for nesting
  scripts/editor/props.js
  scripts/editor/register-blocks.js
Labels: bugfix, improvement

#380 refactoring props helper for new attribute prefixes way
  scripts/editor/props.js
  scripts/helpers/check-attr.js
  scripts/helpers/index.js
Labels: bugfix, improvement

#381 updating blocks/component to incorporate new helpers
  blocks/init/src/Blocks/components/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/components/accordion/components/accordion-options.js
  blocks/init/src/Blocks/components/button/components/button-editor.js
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/card/components/card-editor.js
  blocks/init/src/Blocks/components/card/components/card-options.js
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/heading/components/heading-editor.js
  blocks/init/src/Blocks/components/heading/components/heading-options.js
  blocks/init/src/Blocks/components/heading/components/heading-toolbar.js
  blocks/init/src/Blocks/components/icon/components/icon-editor.js
  blocks/init/src/Blocks/components/icon/components/icon-options.js
  blocks/init/src/Blocks/components/icon/icon.php
  blocks/init/src/Blocks/components/icon/manifest.json
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/components/image-options.js
  blocks/init/src/Blocks/components/image/docs/story.js
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/image/manifest.json
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/components/lists/components/lists-editor.js
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/components/video/components/video-options.js
  blocks/init/src/Blocks/components/video/video.php
  blocks/init/src/Blocks/custom/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/custom/accordion/components/accordion-options.js
  blocks/init/src/Blocks/custom/button/components/button-editor.js
  blocks/init/src/Blocks/custom/button/components/button-options.js
  blocks/init/src/Blocks/custom/button/components/button-toolbar.js
  blocks/init/src/Blocks/custom/card/components/card-editor.js
  blocks/init/src/Blocks/custom/card/components/card-options.js
  blocks/init/src/Blocks/custom/card/components/card-toolbar.js
  blocks/init/src/Blocks/custom/carousel/components/carousel-options.js
  blocks/init/src/Blocks/custom/carousel/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/example/components/example-editor.js
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-options.js
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/heading/components/heading-editor.js
  blocks/init/src/Blocks/custom/heading/components/heading-options.js
  blocks/init/src/Blocks/custom/heading/components/heading-toolbar.js
  blocks/init/src/Blocks/custom/image/components/image-editor.js
  blocks/init/src/Blocks/custom/image/components/image-options.js
  blocks/init/src/Blocks/custom/image/components/image-toolbar.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/custom/lists/components/lists-editor.js
  blocks/init/src/Blocks/custom/lists/components/lists-options.js
  blocks/init/src/Blocks/custom/lists/components/lists-toolbar.js
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-toolbar.js
  blocks/init/src/Blocks/custom/video/components/video-editor.js
  blocks/init/src/Blocks/custom/video/components/video-options.js
  blocks/init/src/Blocks/custom/video/components/video-toolbar.js
Labels: improvement

#382 updating getOptions helpers
  blocks/init/src/Blocks/wrapper/manifest.json
  scripts/editor/get-option-colors.js
  scripts/editor/get-options.js
  scripts/editor/index.js
  scripts/editor/output-css-variables.js
Labels: bugfix, improvement

#383 adding component/blocks corrections for new options helper
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/card/components/card-options.js
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/heading/components/heading-options.js
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js
  scripts/editor/get-options.js
Labels: bugfix, improvement

#379 Setup tests
  .github/workflows/ci.yml
  __mocks__/@eightshift/frontend-libs/mocks/wrapper.js
  __mocks__/@eightshift/frontend-libs/scripts/editor.js
  __mocks__/@eightshift/frontend-libs/scripts/helpers.js
  __mocks__/@wordpress/block-editor.js
  __mocks__/@wordpress/blocks.js
  __mocks__/@wordpress/element.js
  __mocks__/react-html-parser.js
  babel/babel.config.js
  package.json
  scripts/editor/register-blocks.js
  tests/data/block-attributes.js
  tests/data/props-output.js
  tests/data/src/Blocks/components/mock-blockquote/manifest.json
  tests/data/src/Blocks/components/mock-card/manifest.json
  tests/data/src/Blocks/components/mock-paragraph/manifest.json
  tests/data/src/Blocks/components/mock-typography/manifest.json
  tests/data/src/Blocks/custom/mock-blockquote/manifest.json
  tests/helpers/blocks.js
  tests/unit/blocks/blockRegistration.test.js
  tests/unit/scripts/editor/ucfirst.test.js
Labels: improvement

#384 updating php props, removing shared attributes from register method.
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/accordion/accordion.php
  blocks/init/src/Blocks/custom/button/button.php
  blocks/init/src/Blocks/custom/card/card.php
  blocks/init/src/Blocks/custom/heading/heading.php
  blocks/init/src/Blocks/custom/image/image.php
  blocks/init/src/Blocks/custom/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/lists/lists.php
  blocks/init/src/Blocks/custom/paragraph/paragraph.php
  blocks/init/src/Blocks/custom/video/video.php
  scripts/editor/register-blocks.js
  scripts/helpers/check-attr.js
Labels: bugfix, improvement

#389 Eliminate Undefined Attributes
  scripts/editor/output-css-variables.js
Labels: bugfix

#391 Make boilerplate repo configurable in cli
  setup/create-wp-project/src/arguments.js
  setup/create-wp-project/src/commands/theme.js
Labels: improvement

#394 Fix for showWrapper attributes
  scripts/editor/register-blocks.js
Labels: bugfix, improvement

#396 Fix the phpcs errors
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php
  blocks/init/src/Blocks/components/menu/menu.php
Labels: bugfix

#399 Fix for responsive variables mobile first
  scripts/editor/output-css-variables.js
Labels: bugfix, improvement

#401 Set only variablesCustom, variablesEditor and variablesCustomEditor
  scripts/editor/output-css-variables.js
Labels: bugfix, improvement

#403 Fix ColorPaletteCustom label not showing
  scripts/components/color-palette-custom/color-palette-custom.js
Labels: bugfix

#404 Couple more bugfixes
  scripts/components/icon-toggle/icon-toggle.js
  scripts/components/index.js
  styles/override-editor.scss
Labels: bugfix

#400 Feature/updates
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/components/accordion/docs/story.js
  blocks/init/src/Blocks/components/button/components/button-editor.js
  blocks/init/src/Blocks/components/button/docs/story.js
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/card/components/card-editor.js
  blocks/init/src/Blocks/components/card/components/card-options.js
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/card/docs/story.js
  blocks/init/src/Blocks/components/card/manifest.json
  blocks/init/src/Blocks/components/copyright/components/copyright-editor.js
  blocks/init/src/Blocks/components/copyright/copyright.php
  blocks/init/src/Blocks/components/copyright/docs/story.js
  blocks/init/src/Blocks/components/drawer/components/drawer-editor.js
  blocks/init/src/Blocks/components/drawer/docs/story.js
  blocks/init/src/Blocks/components/drawer/drawer.php
  blocks/init/src/Blocks/components/hamburger/components/hamburger-editor.js
  blocks/init/src/Blocks/components/hamburger/hamburger.php
  blocks/init/src/Blocks/components/head/head.php
  blocks/init/src/Blocks/components/head/manifest.json
  blocks/init/src/Blocks/components/heading/components/heading-editor.js
  blocks/init/src/Blocks/components/heading/docs/story.js
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/components/icon/components/icon-editor.js
  blocks/init/src/Blocks/components/icon/components/icon-options.js
  blocks/init/src/Blocks/components/icon/docs/story.js
  blocks/init/src/Blocks/components/icon/icon.php
  blocks/init/src/Blocks/components/icon/manifest.json
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/docs/story.js
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/custom/carousel/docs/readme.mdx
  blocks/init/src/Blocks/custom/carousel/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/columns/manifest.json
  blocks/init/src/Blocks/custom/group/manifest.json
  package.json
Labels: improvement

#407 Feature/fix webpack require error current ver
  webpack/project.js
Labels: bugfix

#406 Fixed webpack require error
  webpack/project.js
Labels: bugfix

#409 adding method for all blocks inserter
  scripts/editor/index.js
  scripts/editor/inserter.js
Labels: improvement

#411 Fix phpstan issues
  .editorconfig
  .github/workflows/ci.yml
  .github/workflows/tests.yml
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/copyright/copyright.php
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php
  blocks/init/src/Blocks/components/menu/menu.php
  blocks/init/src/Blocks/components/social-links/social-links.php
  blocks/init/src/Blocks/components/video/video.php
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/video/video.php
  blocks/init/src/Blocks/wrapper/wrapper.php
  composer.json
  phpcs.xml.dist
  phpstan.neon.dist
Labels: bugfix, improvement

#410 Fix for default breakpoints
  scripts/editor/output-css-variables.js
Labels: bugfix, improvement
