Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-05, with the labels that each got.

#330 Feature/check attr responsive
  scripts/editor/output-css-variables.js
Labels: improvement

#331 updating responsive-select
  scripts/editor/output-css-variables.js
Labels: improvement

#332 updating responsive-select
  blocks/init/src/Blocks/components/heading/components/heading-editor.js
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/custom/image/components/image-editor.js
  blocks/init/src/Blocks/custom/image/image.php
  scripts/editor/output-css-variables.js
Labels: improvement

#333 updating variables
  scripts/editor/index.js
  scripts/editor/output-css-variables.js
Labels: improvement

#337 updating variables output
  scripts/editor/output-css-variables.js
Labels: bugfix

#338 Icon update
  scripts/editor/icons/icons.js
  scripts/editor/index.js
Labels: improvement

#339 UX improvements
  blocks/init/src/Blocks/wrapper/components/wrapper-options.js
  scripts/components/custom-select/custom-select.js
  scripts/components/help-modal/help-modal.js
  scripts/components/option-picker/docs/readme.mdx
  scripts/components/option-picker/option-picker.js
  scripts/components/responsive/responsive.js
  scripts/editor/icons/icons.js
  styles/override-editor.scss
Labels: improvement

#341 Optional undefinedAllowed parameter on checkAttr
  scripts/helpers/check-attr.js
Labels: improvement

#343 updating props helper
  blocks/init/src/Blocks/components/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/heading/components/heading-options.js
  blocks/init/src/Blocks/components/icon/components/icon-options.js
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/components/social-links/components/social-links-editor.js
  blocks/init/src/Blocks/components/video-button/components/video-button-editor.js
  blocks/init/src/Blocks/components/video/components/video-options.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
Labels: bug, bugfix

#346 Fix escaping issues
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/head/head.php
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/components/lists/lists.php
  blocks/init/src/Blocks/components/paragraph/paragraph.php
  blocks/init/src/Blocks/components/video/video.php
  blocks/init/src/Blocks/custom/accordion/accordion.php
  blocks/init/src/Blocks/custom/button/button.php
  blocks/init/src/Blocks/custom/card/card.php
  blocks/init/src/Blocks/custom/column/column.php
  blocks/init/src/Blocks/custom/columns/columns.php
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/heading/heading.php
  blocks/init/src/Blocks/custom/image/image.php
  blocks/init/src/Blocks/custom/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/lists/lists.php
  blocks/init/src/Blocks/custom/paragraph/paragraph.php
  blocks/init/src/Blocks/custom/video/video.php
  scripts/editor/output-css-variables.js
  styles/scss/functions/_calc-grid-width.scss
  styles/scss/mixins/_modifiers-range.scss
Labels: bugfix, improvement

#342 DX improvements
  scripts/components/color-palette-custom/color-palette-custom.js
  scripts/components/custom-select/custom-select.js
  scripts/components/heading-level/heading-level.js
  scripts/components/help-modal/help-modal.js
  scripts/components/link-toolbar-button/link-toolbar-button.js
  scripts/components/option-picker/option-picker.js
  scripts/components/responsive/responsive.js
  scripts/components/server-side-render/server-side-render.js
  scripts/editor/get-actions.js
  scripts/editor/get-options.js
  scripts/editor/icons/icons.js
  scripts/editor/output-css-variables.js
  scripts/editor/paste-handler.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
  scripts/editor/ucfirst.js
  scripts/helpers/camelize.js
  scripts/helpers/check-attr.js
  scripts/helpers/cookies.js
  scripts/helpers/debounce.js
  scripts/helpers/devices.js
  scripts/helpers/dynamic-import.js
  scripts/helpers/element-children-height.js
  scripts/helpers/escape-string.js
  scripts/helpers/navigator.js
  scripts/helpers/responsive-selectors.js
  scripts/helpers/selector.js
Labels: improvement

#350 Empty placeholder fix
  styles/override-editor.scss
Labels: improvement

#348 fixing packages version
  package.json
  styles/scss/functions/_calc-column-width.scss
Labels: bug, bugfix

#358 Add variablesEditor to Manifest
  scripts/editor/output-css-variables.js
Labels: improvement
