Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-04, with the labels that each got.

#311 updating helper for css variables
  blocks/init/src/Blocks/components/heading/manifest.json
  scripts/editor/output-css-variables.js
Labels: improvement

#313 Fix setup script overriding libs and frontend libs branches
  .gitignore
  setup/create-wp-project/package.json
  setup/create-wp-project/src/basics/command-line.js
  setup/create-wp-project/src/commands/plugin.js
  setup/create-wp-project/src/commands/theme.js
  setup/create-wp-project/src/dependencies.js
Labels: bugfix

#316 Block icon display fixes
  scripts/editor/register-blocks.js
  styles/override-editor.scss
Labels: improvement

#315 Storybook icon improvements and icon tweaks/additions
  scripts/editor/icons/icons.js
  scripts/editor/icons/readme.mdx
  scripts/editor/icons/story.js
Labels: improvement

#318 Link toolbar button
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/button/components/button-toolbar.js
  blocks/init/src/Blocks/components/button/manifest.json
  blocks/init/src/Blocks/components/link/components/link-options.js
  blocks/init/src/Blocks/components/link/components/link-toolbar.js
  scripts/components/index.js
  scripts/components/link-toolbar-button/docs/readme.mdx
  scripts/components/link-toolbar-button/docs/story.js
  scripts/components/link-toolbar-button/link-toolbar-button.js
Labels: improvement

#320 Option select component
  scripts/components/index.js
  scripts/components/link-toolbar-button/docs/story.js
  scripts/components/link-toolbar-button/link-toolbar-button.js
  scripts/components/option-picker/docs/readme.mdx
  scripts/components/option-picker/docs/story.js
  scripts/components/option-picker/option-picker.js
  scripts/editor/icons/icons.js
Labels: improvement

#321 Make Link semantically correct
  blocks/init/src/Blocks/components/link/link.php
Labels: improvement

#322 Custom select async option
  scripts/components/custom-select/custom-select.js
  scripts/components/custom-select/docs/readme.mdx
  scripts/components/custom-select/docs/story.js
Labels: improvement

#324 Icon new picker (and more CustomSelect goodies)
  blocks/init/src/Blocks/components/icon/components/icon-options.js
  blocks/init/src/Blocks/components/icon/icon-editor.scss
  blocks/init/src/Blocks/components/icon/manifest.json
  scripts/components/custom-select/custom-select.js
  scripts/components/custom-select/docs/readme.mdx
  scripts/components/custom-select/docs/story.js
Labels: improvement

#304 Dart Sass implementation
  package.json
  styles/scss/mixins/_link-modifiers.scss
  styles/scss/mixins/_modifiers-deep.scss
  webpack/base.js
  webpack/storybook.js
Labels: improvement, scss

#326 Feature/image
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/head/head.php
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/components/image-options.js
  blocks/init/src/Blocks/components/image/components/image-toolbar.js
  blocks/init/src/Blocks/components/image/docs/story.js
  blocks/init/src/Blocks/components/image/image-style.scss
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/image/manifest.json
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/accordion/accordion.php
  blocks/init/src/Blocks/custom/button/button.php
  blocks/init/src/Blocks/custom/card/card.php
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/heading/heading.php
  blocks/init/src/Blocks/custom/image/components/image-editor.js
  blocks/init/src/Blocks/custom/image/components/image-toolbar.js
  blocks/init/src/Blocks/custom/image/image-style.scss
  blocks/init/src/Blocks/custom/image/image.php
  blocks/init/src/Blocks/custom/image/manifest.json
  blocks/init/src/Blocks/custom/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/link/link.php
  blocks/init/src/Blocks/custom/lists/lists.php
  blocks/init/src/Blocks/custom/paragraph/paragraph.php
  blocks/init/src/Blocks/custom/video/video.php
  blocks/init/src/Blocks/wrapper/wrapper.php
  composer.json
  scripts/editor/output-css-variables.js
Labels: improvement

#328 updating new helper
  scripts/editor/output-css-variables.js
  scripts/helpers/check-attr.js
  scripts/helpers/index.js
Labels: improvement

#329 Feature/check attr responsive
  scripts/editor/output-css-variables.js
Labels: improvement
