Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-09, with the labels that each got.

#433 Fix storybook
  scripts/editor/index.js
  scripts/editor/register-blocks.js
Labels: bugfix

#434 Remove console logs
  scripts/components/option-picker/docs/story.js
  scripts/components/simple-vertical-single-select/docs/readme.mdx
  scripts/editor/override-inner-block-attributes.js
Labels: improvement, bugfix

#430 New quote block
  blocks/init/src/Blocks/components/quote/components/quote-editor.js
  blocks/init/src/Blocks/components/quote/components/quote-options.js
  blocks/init/src/Blocks/components/quote/components/quote-toolbar.js
  blocks/init/src/Blocks/components/quote/docs/readme.mdx
  blocks/init/src/Blocks/components/quote/docs/story.js
  blocks/init/src/Blocks/components/quote/manifest.json
  blocks/init/src/Blocks/components/quote/quote-style.scss
  blocks/init/src/Blocks/components/quote/quote.php
  blocks/init/src/Blocks/custom/quote/components/quote-editor.js
  blocks/init/src/Blocks/custom/quote/components/quote-options.js
  blocks/init/src/Blocks/custom/quote/components/quote-toolbar.js
  blocks/init/src/Blocks/custom/quote/docs/readme.mdx
  blocks/init/src/Blocks/custom/quote/docs/story.js
  blocks/init/src/Blocks/custom/quote/manifest.json
  blocks/init/src/Blocks/custom/quote/quote-block.js
  blocks/init/src/Blocks/custom/quote/quote-style.scss
  blocks/init/src/Blocks/custom/quote/quote.php
Labels: improvement, new block

#440 Fix heading <-> paragraph transform issues
  blocks/init/src/Blocks/custom/heading/heading-transforms.js
  blocks/init/src/Blocks/custom/paragraph/paragraph-transforms.js
Labels: bugfix

#441 Babel "polyfill loaded twice" warning fix
  blocks/init/assets/scripts/application.js
  blocks/init/src/Blocks/assets/scripts/application-blocks.js
Labels: bugfix

#442 Paragraph fix
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-editor.js
  scripts/editor/register-blocks.js
Labels: improvement, bugfix

#443 Add paragraph as a default block in the editor
  blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js
Labels: improvement, feature request
