Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-01, with the labels that each got.

#221 Add inline font color mixin
  styles/scss/mixins/_all.scss
  styles/scss/mixins/_inline-font-colors.scss
Labels: improvement

#223 Feature/updates
  blocks/init/src/Blocks/components/button/button-style.scss
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/button/components/button-editor.js
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/image-style.scss
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/link/components/link-editor.js
  blocks/init/src/Blocks/components/link/link-style.scss
  blocks/init/src/Blocks/components/link/link.php
Labels: bug

#225 Add browser sync to package.json
  package.json
Labels: bug

#226 updating Webpack externals
  babel/babel.config.js
  package-lock.json
  package.json
  webpack/base.js
Labels: bug

#227 Add codeowners file
  .github/CODEOWNERS
Labels: improvement

#228 Update head.php
  blocks/init/src/Blocks/components/head/head.php
Labels: improvement

#230 Fix onChange property for videoType attribute.
  blocks/init/src/Blocks/components/video/components/video-options.js
Labels: bugfix

#229 Feature/jumbotron
  .storybook/babel.config.js
  babel/babel.config.js
  blocks/init/src/Blocks/components/button/components/button-toolbar.js
  blocks/init/src/Blocks/components/heading/components/heading-toolbar.js
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/components/image-toolbar.js
  blocks/init/src/Blocks/components/image/docs/story.js
  blocks/init/src/Blocks/components/image/image-style.scss
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/image/manifest.json
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/components/jumbotron/docs/readme.mdx
  blocks/init/src/Blocks/components/jumbotron/docs/story.js
  blocks/init/src/Blocks/components/jumbotron/jumbotron-style.scss
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/components/jumbotron/manifest.json
  blocks/init/src/Blocks/components/link/components/link-toolbar.js
  blocks/init/src/Blocks/components/lists/components/lists-toolbar.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-toolbar.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/custom/jumbotron/docs/readme.mdx
  blocks/init/src/Blocks/custom/jumbotron/docs/story.js
  blocks/init/src/Blocks/custom/jumbotron/jumbotron-block.js
  blocks/init/src/Blocks/custom/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/jumbotron/manifest.json
Labels: New Block, New Component

#232 updating typo
  blocks/init/src/Blocks/components/card/card.php
Labels: improvement

#236 updating new helper
  blocks/init/src/Blocks/components/image/image-style.scss
  scripts/helpers/camelize.js
  scripts/helpers/index.js
Labels: improvement

#237 updating multilevel nested columns
  blocks/init/src/Blocks/custom/columns/columns-editor.scss
  blocks/init/src/Blocks/custom/columns/columns.php
  blocks/init/src/Blocks/custom/columns/components/columns-editor.js
  blocks/init/src/Blocks/custom/columns/styles/_shared.scss
Labels: bug, bugfix

#242 Add component color helper
  babel/babel.config.js
  package.json
  scripts/editor/get-option-colors.js
  tests/unit/scripts/editor/optionColors.test.js
Labels: improvement

#246 updating column with align
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/heading/components/heading-options.js
  blocks/init/src/Blocks/components/link/components/link-options.js
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/custom/column/column-hooks.js
  blocks/init/src/Blocks/custom/column/column.php
  blocks/init/src/Blocks/custom/column/components/column-options.js
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/column/styles/_shared.scss
Labels: improvement
