Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-11, with the labels that each got.

#482 Infinum ESLint config version bump
  package.json
Labels: dependencies

#483 Remove example attributes. Adjust blockDetails helper
  blocks/init/src/Blocks/variations/button-block/manifest.json
  blocks/init/src/Blocks/variations/card-simple/manifest.json
  scripts/storybook/helpers.js
Labels: improvement

#481 Collapsable ComponentUseToggle
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
  scripts/components/collapsable-component-use-toggle/docs/readme.mdx
  scripts/components/collapsable-component-use-toggle/docs/story.js
  styles/override-editor.scss
Labels: improvement, new component

#486 Fix overlapping issue
  scripts/components/custom-select/custom-select.js
  styles/override-editor.scss
Labels: bugfix

#500 CustomSelect improvements
  scripts/components/custom-select/custom-select.js
Labels: improvement

#502 Visual enhancements and a couple of fixes
  scripts/components/custom-select/custom-select.js
  scripts/editor/icons/icons.js
  scripts/editor/icons/story.js
  styles/override-editor.scss
Labels: improvement

#505 Minor icon update
  scripts/editor/icons/icons.js
Labels: improvement

#506 Custom select async multi-select setAttr fix
  scripts/components/custom-select/custom-select.js
Labels: bugfix

#507 Lists component improvements
  blocks/init/src/Blocks/components/lists/components/lists-editor.js
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/lists/lists.php
  blocks/init/src/Blocks/components/lists/manifest.json
Labels: bug

#510 CustomSelect overlap fixes and fetchWpApi fix
  scripts/components/custom-select/custom-select.js
  scripts/editor/fetch-wp-api.js
  styles/override-editor.scss
Labels: improvement, bugfix

#513 Fix simple value select not being selected
  scripts/components/custom-select/custom-select.js
Labels: bug
