Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-12, with the labels that each got.

#512 Feature - Throttle implementation
  scripts/helpers/debounce.js
  scripts/helpers/index.js
  scripts/helpers/throttle.js
Labels: improvement, feature request

#520 Custom select cache nullguard
  scripts/components/custom-select/custom-select.js
Labels: bugfix

#521 CustomSelect cache retreival fix
  scripts/components/custom-select/custom-select.js
Labels: bugfix

#523 Block attribute deprecation/migration
  blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js
  scripts/editor/register-blocks.js
Labels: improvement

#525 Fix #419
  setup/create-wp-project/src/basics/argument-operations.js
Labels: bugfix

#530 adding overrides option in block registration
  blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js
  scripts/editor/register-blocks.js
Labels: improvement

#528 Fix/set correct installation dir path
  setup/create-wp-project/src/basics/files.js
  setup/create-wp-project/src/commands/plugin.js
  setup/create-wp-project/src/commands/theme.js
Labels: bugfix
