Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-03, with the labels that each got.

#296 adding implementation to the helper
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/button/components/button-toolbar.js
  blocks/init/src/Blocks/components/button/docs/story.js
  blocks/init/src/Blocks/components/button/manifest.json
  blocks/init/src/Blocks/components/card/components/card-options.js
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/heading/components/heading-options.js
  blocks/init/src/Blocks/components/heading/components/heading-toolbar.js
  blocks/init/src/Blocks/components/heading/docs/story.js
  blocks/init/src/Blocks/components/heading/manifest.json
  blocks/init/src/Blocks/components/link/components/link-options.js
  blocks/init/src/Blocks/components/link/components/link-toolbar.js
  blocks/init/src/Blocks/components/link/docs/story.js
  blocks/init/src/Blocks/components/link/manifest.json
  blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-toolbar.js
  blocks/init/src/Blocks/components/paragraph/docs/story.js
  blocks/init/src/Blocks/components/paragraph/manifest.json
  blocks/init/src/Blocks/custom/card/components/card-options.js
  blocks/init/src/Blocks/custom/card/components/card-toolbar.js
  blocks/init/src/Blocks/custom/card/manifest.json
  scripts/editor/get-options.js
  scripts/editor/index.js
Labels: improvement

#297 updating manifest scope
  blocks/init/src/Blocks/components/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/components/button/components/button-options.js
  blocks/init/src/Blocks/components/button/components/button-toolbar.js
  blocks/init/src/Blocks/components/heading/components/heading-options.js
  blocks/init/src/Blocks/components/heading/components/heading-toolbar.js
  blocks/init/src/Blocks/components/icon/components/icon-editor.js
  blocks/init/src/Blocks/components/icon/components/icon-options.js
  blocks/init/src/Blocks/components/image/components/image-options.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/components/link/components/link-options.js
  blocks/init/src/Blocks/components/link/components/link-toolbar.js
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/lists/components/lists-toolbar.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-toolbar.js
  blocks/init/src/Blocks/components/social-links/components/social-links-editor.js
  blocks/init/src/Blocks/components/video-button/components/video-button-editor.js
  blocks/init/src/Blocks/components/video/components/video-options.js
  blocks/init/src/Blocks/custom/carousel/components/carousel-options.js
  blocks/init/src/Blocks/custom/column/components/column-options.js
  blocks/init/src/Blocks/custom/columns/components/columns-options.js
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-options.js
  blocks/init/src/Blocks/custom/featured-posts/components/featured-posts-options.js
  blocks/init/src/Blocks/wrapper/components/wrapper-options.js
  scripts/editor/get-options.js
Labels: bugfix

#299 Fixed image alignment
  blocks/init/src/Blocks/components/image/image-style.scss
Labels: bugfix, improvement

#302 adding option for css variables
  webpack/base.js
  webpack/helpers.js
  webpack/index.js
  webpack/storybook.js
Labels: improvement

#306 Feature/props helper
  scripts/editor/index.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
Labels: improvement

#309 updating blocks
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/card/components/card-editor.js
  blocks/init/src/Blocks/components/card/components/card-options.js
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/accordion/accordion.php
  blocks/init/src/Blocks/custom/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/custom/accordion/components/accordion-options.js
  blocks/init/src/Blocks/custom/button/button.php
  blocks/init/src/Blocks/custom/button/components/button-editor.js
  blocks/init/src/Blocks/custom/button/components/button-options.js
  blocks/init/src/Blocks/custom/button/components/button-toolbar.js
  blocks/init/src/Blocks/custom/card/card.php
  blocks/init/src/Blocks/custom/card/components/card-editor.js
  blocks/init/src/Blocks/custom/card/components/card-options.js
  blocks/init/src/Blocks/custom/card/components/card-toolbar.js
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-editor.js
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/heading/components/heading-editor.js
  blocks/init/src/Blocks/custom/heading/components/heading-options.js
  blocks/init/src/Blocks/custom/heading/components/heading-toolbar.js
  blocks/init/src/Blocks/custom/heading/heading.php
  blocks/init/src/Blocks/custom/image/components/image-editor.js
  blocks/init/src/Blocks/custom/image/components/image-options.js
  blocks/init/src/Blocks/custom/image/components/image-toolbar.js
  blocks/init/src/Blocks/custom/image/image.php
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/custom/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/custom/jumbotron/jumbotron.php
  blocks/init/src/Blocks/custom/link/components/link-editor.js
  blocks/init/src/Blocks/custom/link/components/link-options.js
  blocks/init/src/Blocks/custom/link/components/link-toolbar.js
  blocks/init/src/Blocks/custom/link/link.php
  blocks/init/src/Blocks/custom/lists/components/lists-editor.js
  blocks/init/src/Blocks/custom/lists/components/lists-options.js
  blocks/init/src/Blocks/custom/lists/components/lists-toolbar.js
  blocks/init/src/Blocks/custom/lists/lists.php
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-options.js
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-toolbar.js
  blocks/init/src/Blocks/custom/paragraph/paragraph.php
  blocks/init/src/Blocks/custom/video/components/video-editor.js
  blocks/init/src/Blocks/custom/video/components/video-options.js
  blocks/init/src/Blocks/custom/video/components/video-toolbar.js
  blocks/init/src/Blocks/custom/video/video.php
  scripts/editor/props.js
Labels: improvement

#308 Improved SSR component
  scripts/components/index.js
  scripts/components/server-side-render/docs/readme.mdx
  scripts/components/server-side-render/docs/story.js
  scripts/components/server-side-render/server-side-render.js
Labels: improvement
