Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-02, with the labels that each got.

#249 Remove unnecessary stuff
  setup/create-wp-project/src/arguments.js
  setup/create-wp-project/src/commands/plugin.js
  setup/create-wp-project/src/search-replace.js
  tests/unit/create-wp-project/arguments.test.js
Labels: improvement

#251 Update paragraph icon
  blocks/init/src/Blocks/custom/paragraph/manifest.json
Labels: improvement

#252 Change heading icon
  blocks/init/src/Blocks/custom/heading/manifest.json
Labels: improvement

#256 Helper modal updates
  scripts/components/help-modal/data.js
  scripts/components/help-modal/help-modal.js
  scripts/editor/icons.js
  styles/override-editor.scss
Labels: improvement

#253 Adding Yoast Seo helper
  blocks/init/src/Blocks/components/accordion/manifest.json
  blocks/init/src/Blocks/components/button/manifest.json
  blocks/init/src/Blocks/components/copyright/manifest.json
  blocks/init/src/Blocks/components/heading/manifest.json
  blocks/init/src/Blocks/components/link/manifest.json
  blocks/init/src/Blocks/components/lists/manifest.json
  blocks/init/src/Blocks/components/paragraph/manifest.json
  blocks/init/src/Blocks/components/scroll-to-top/manifest.json
  scripts/editor/index.js
  scripts/editor/yoast-seo.js
Labels: improvement

#248 Cleanup
  blocks/init/src/Blocks/components/accordion/assets/accordion.js
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/card/components/card-editor.js
  blocks/init/src/Blocks/components/card/components/card-options.js
  blocks/init/src/Blocks/components/card/components/card-toolbar.js
  blocks/init/src/Blocks/components/header/docs/story.js
  blocks/init/src/Blocks/components/image/components/image-editor.js
  blocks/init/src/Blocks/components/image/components/image-options.js
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/image/manifest.json
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-editor.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-options.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/components/link/link.php
  blocks/init/src/Blocks/components/search-bar/components/search-bar-editor.js
  blocks/init/src/Blocks/components/search-bar/manifest.json
  blocks/init/src/Blocks/components/search-bar/search-bar-style.scss
  blocks/init/src/Blocks/components/search-bar/search-bar.php
  blocks/init/src/Blocks/components/share/assets/share.js
  blocks/init/src/Blocks/components/video/components/video-editor.js
  blocks/init/src/Blocks/components/video/video-style.scss
  blocks/init/src/Blocks/components/video/video.php
  blocks/init/src/Blocks/custom/card/components/card-toolbar.js
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts.php
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-options.js
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  scripts/components/color-palette-custom/color-palette-custom.js
  scripts/components/color-palette-custom/docs/story.js
  scripts/editor/get-actions.js
  scripts/editor/index.js
  scripts/editor/register-blocks.js
  scripts/helpers/camelize.js
  scripts/helpers/check-attr.js
  scripts/helpers/cookies.js
  scripts/helpers/debounce.js
  scripts/helpers/devices.js
  scripts/helpers/dynamic-import.js
  scripts/helpers/element-children-height.js
  scripts/helpers/escape-string.js
  scripts/helpers/navigator.js
  scripts/helpers/responsive-selectors.js
  scripts/helpers/selector.js
  scripts/storybook/helpers.js
  scripts/storybook/parts.js
  setup/create-wp-project/src/basics/argument-operations.js
  setup/create-wp-project/src/basics/files.js
  setup/create-wp-project/src/dependencies.js
  webpack/helpers.js
  webpack/index.js
Labels: bugfix

#259 Block icon updates
  blocks/init/src/Blocks/custom/accordion/manifest.json
  blocks/init/src/Blocks/custom/button/manifest.json
  blocks/init/src/Blocks/custom/card/manifest.json
  blocks/init/src/Blocks/custom/carousel/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/columns/manifest.json
  blocks/init/src/Blocks/custom/example/manifest.json
  blocks/init/src/Blocks/custom/featured-categories-posts/manifest.json
  blocks/init/src/Blocks/custom/featured-categories/manifest.json
  blocks/init/src/Blocks/custom/featured-posts/manifest.json
  blocks/init/src/Blocks/custom/group/manifest.json
  blocks/init/src/Blocks/custom/heading/manifest.json
  blocks/init/src/Blocks/custom/image/manifest.json
  blocks/init/src/Blocks/custom/jumbotron/manifest.json
  blocks/init/src/Blocks/custom/link/manifest.json
  blocks/init/src/Blocks/custom/lists/manifest.json
  blocks/init/src/Blocks/custom/paragraph/manifest.json
  blocks/init/src/Blocks/custom/video/manifest.json
  blocks/init/src/Blocks/manifest.json
  blocks/init/src/Blocks/variations/button-block/manifest.json
  blocks/init/src/Blocks/variations/card-simple/manifest.json
Labels: improvement

#260 Add block icons to library
  scripts/editor/icons.js
Labels: improvement

#261 adding icons to storybook
  .storybook/main.js
  package.json
  scripts/components/help-modal/data.js
  scripts/editor/icons/icons.js
  scripts/editor/icons/readme.mdx
  scripts/editor/icons/story.js
  scripts/editor/index.js
  scripts/plugins/index.js
  scripts/plugins/yoast-seo.js
Labels: improvement

#247 Add icon component
  blocks/init/src/Blocks/components/icon/components/icon-editor.js
  blocks/init/src/Blocks/components/icon/components/icon-options.js
  blocks/init/src/Blocks/components/icon/docs/readme.mdx
  blocks/init/src/Blocks/components/icon/docs/story.js
  blocks/init/src/Blocks/components/icon/icon-style.scss
  blocks/init/src/Blocks/components/icon/icon.php
  blocks/init/src/Blocks/components/icon/manifest.json
Labels: new component

#262 Add alt setting when using image placeholder
  blocks/init/src/Blocks/components/image/components/image-options.js
Labels: improvement

#267 updating browserSync https
  webpack/development.js
  webpack/helpers.js
  webpack/index.js
Labels: improvement

#266 updating fix to remove php file from build
  webpack/base.js
Labels: bug, bugfix

#268 Fix namespace generation
  setup/create-wp-project/src/arguments.js
  tests/unit/create-wp-project/arguments.test.js
Labels: improvement

#270 Lets try adding unit tests to actions
  .github/workflows/ci.yml
  package.json
Labels: improvement

#275 Fix css class and selector
  blocks/init/src/Blocks/components/button/assets/index.js
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/link/assets/index.js
  blocks/init/src/Blocks/components/link/link.php
Labels: bugfix

#273 updating fix
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
Labels: bug, bugfix

#278 Hotfix/featured posts
  blocks/init/src/Blocks/components/search-bar/search-bar.php
  blocks/init/src/Blocks/custom/featured-categories-posts/components/featured-categories-posts-editor.js
  blocks/init/src/Blocks/custom/featured-categories-posts/components/featured-categories-posts-options.js
  blocks/init/src/Blocks/custom/featured-categories-posts/docs/readme.mdx
  blocks/init/src/Blocks/custom/featured-categories-posts/docs/story.js
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts-block.js
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts-style.scss
  blocks/init/src/Blocks/custom/featured-categories-posts/featured-categories-posts.php
  blocks/init/src/Blocks/custom/featured-categories-posts/manifest.json
  blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-options.js
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-posts/components/featured-posts-options.js
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/featured-posts/manifest.json
  package.json
  scripts/components/custom-select/custom-select.js
  scripts/components/custom-select/docs/readme.mdx
  scripts/components/custom-select/docs/story.js
  scripts/components/index.js
Labels: improvement, new component

#282 Add options to feature-posts manifest
  blocks/init/src/Blocks/custom/featured-posts/manifest.json
Labels: bugfix

#280 Icon updates
  blocks/init/src/Blocks/custom/accordion/manifest.json
  blocks/init/src/Blocks/custom/button/manifest.json
  blocks/init/src/Blocks/custom/card/manifest.json
  blocks/init/src/Blocks/custom/carousel/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/columns/manifest.json
  blocks/init/src/Blocks/custom/example/manifest.json
  blocks/init/src/Blocks/custom/group/manifest.json
  blocks/init/src/Blocks/custom/heading/manifest.json
  blocks/init/src/Blocks/custom/image/manifest.json
  blocks/init/src/Blocks/custom/jumbotron/manifest.json
  blocks/init/src/Blocks/custom/link/manifest.json
  blocks/init/src/Blocks/custom/lists/manifest.json
  blocks/init/src/Blocks/custom/paragraph/manifest.json
  blocks/init/src/Blocks/custom/video/manifest.json
  blocks/init/src/Blocks/manifest.json
  blocks/init/src/Blocks/variations/button-block/manifest.json
  blocks/init/src/Blocks/variations/card-simple/manifest.json
  scripts/editor/icons/icons.js
  scripts/editor/register-blocks.js
Labels: improvement

#276 Paragraph UX improvements
  blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/components/paragraph/manifest.json
  blocks/init/src/Blocks/custom/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/custom/paragraph/manifest.json
  scripts/editor/index.js
  scripts/editor/paste-handler.js
  scripts/editor/register-blocks.js
Labels: improvement

#284 New icons
  blocks/init/src/Blocks/custom/accordion/manifest.json
  blocks/init/src/Blocks/custom/button/manifest.json
  blocks/init/src/Blocks/custom/card/manifest.json
  blocks/init/src/Blocks/custom/carousel/manifest.json
  blocks/init/src/Blocks/custom/column/manifest.json
  blocks/init/src/Blocks/custom/columns/manifest.json
  blocks/init/src/Blocks/custom/example/manifest.json
  blocks/init/src/Blocks/custom/group/manifest.json
  blocks/init/src/Blocks/custom/heading/manifest.json
  blocks/init/src/Blocks/custom/image/manifest.json
  blocks/init/src/Blocks/custom/jumbotron/manifest.json
  blocks/init/src/Blocks/custom/link/manifest.json
  blocks/init/src/Blocks/custom/lists/manifest.json
  blocks/init/src/Blocks/custom/paragraph/manifest.json
  blocks/init/src/Blocks/custom/video/manifest.json
  blocks/init/src/Blocks/variations/button-block/manifest.json
  blocks/init/src/Blocks/variations/card-simple/manifest.json
  scripts/editor/icons/icons.js
Labels: improvement

#293 Update .gitattributes
  .gitattributes
Labels: bugfix, improvement

#294 updating allowed-formats
  blocks/init/src/Blocks/components/accordion/components/accordion-editor.js
  blocks/init/src/Blocks/components/button/components/button-editor.js
  blocks/init/src/Blocks/components/heading/components/heading-editor.js
  blocks/init/src/Blocks/components/link/components/link-editor.js
  blocks/init/src/Blocks/components/lists/components/lists-editor.js
  blocks/init/src/Blocks/custom/example/components/example-editor.js
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
Labels: bug
