Repository infinum/eightshift-frontend-libs, pull requests merged in 2021-08, with the labels that each got.

#416 Fix the possible undefined value
  blocks/init/src/Blocks/wrapper/components/wrapper-options.js
  scripts/components/responsive/docs/story.js
Labels: bugfix

#415 updating helpers docs
  scripts/editor/get-actions.js
  scripts/editor/get-options.js
  scripts/editor/get-palette-colors.js
  scripts/editor/icons/icons.js
  scripts/editor/index.js
  scripts/editor/inserter.js
  scripts/editor/output-css-variables.js
  scripts/editor/override-inner-block-attributes.js
  scripts/editor/paste-handler.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
  scripts/editor/ucfirst.js
  scripts/helpers/camelize.js
  scripts/helpers/check-attr.js
  scripts/helpers/cookies.js
  scripts/helpers/debounce.js
  scripts/helpers/devices.js
  scripts/helpers/dynamic-import.js
  scripts/helpers/element-children-height.js
  scripts/helpers/escape-string.js
  scripts/helpers/index.js
  scripts/helpers/navigator.js
  scripts/helpers/responsive-selectors.js
  scripts/helpers/selector.js
  scripts/helpers/text-helpers.js
  scripts/plugins/yoast-seo.js
  scripts/storybook/helpers.js
Labels: improvement

#423 Readding missing BlockIcon
  scripts/editor/icons/icons.js
  scripts/editor/index.js
Labels: bugfix

#427 Add modal component
  blocks/init/src/Blocks/components/modal/assets/index.js
  blocks/init/src/Blocks/components/modal/assets/modal.js
  blocks/init/src/Blocks/components/modal/components/modal-editor.js
  blocks/init/src/Blocks/components/modal/components/modal-options.js
  blocks/init/src/Blocks/components/modal/docs/readme.mdx
  blocks/init/src/Blocks/components/modal/docs/story.js
  blocks/init/src/Blocks/components/modal/manifest.json
  blocks/init/src/Blocks/components/modal/modal-style.scss
  blocks/init/src/Blocks/components/modal/modal.php
Labels: improvement, new component
