Repository infinum/eightshift-frontend-libs, pull requests merged in 2022-03, with the labels that each got.

#573 Separate conditions for projectName and description in create-wp-project
  setup/create-wp-project/src/search-replace.js
Labels: bugfix

#574 Fixes for Quote block/component a11y
  blocks/init/src/Blocks/components/paragraph/manifest.json
  blocks/init/src/Blocks/components/quote/components/quote-editor.js
  blocks/init/src/Blocks/components/quote/components/quote-options.js
  blocks/init/src/Blocks/components/quote/components/quote-toolbar.js
  blocks/init/src/Blocks/components/quote/manifest.json
  blocks/init/src/Blocks/components/quote/quote.php
  blocks/init/src/Blocks/custom/quote/components/quote-toolbar.js
Labels: bugfix, a11y

#579 A11y: Use list markup for card groups
  blocks/init/src/Blocks/custom/featured-categories/featured-categories-style.scss
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-posts/featured-posts-style.scss
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
Labels: improvement, a11y

#578 A11y: Small improvements to heading and paragraph components
  blocks/init/src/Blocks/components/heading/heading.php
  blocks/init/src/Blocks/components/paragraph/paragraph.php
Labels: improvement, a11y

#583 Collapsable component
  blocks/init/src/Blocks/components/quote/docs/story.js
  scripts/components/collapsable/collapsable.js
  scripts/components/collapsable/collapsable.scss
  scripts/components/collapsable/docs/readme.mdx
  scripts/components/collapsable/docs/story.js
  scripts/components/index.js
  scripts/index.js
  styles/es-component-styles.scss
Labels: new component

#582 A11y: Video captions
  blocks/init/src/Blocks/components/video/components/video-options.js
  blocks/init/src/Blocks/components/video/manifest.json
  scripts/editor/icons/icons.js
Labels: improvement, a11y

#585 Fix lint errors after Eightshift Coding Standards 1.4 release
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/button/button.php
  blocks/init/src/Blocks/components/card/card.php
  blocks/init/src/Blocks/components/copyright/copyright.php
  blocks/init/src/Blocks/components/drawer/drawer.php
  blocks/init/src/Blocks/components/hamburger/hamburger.php
  blocks/init/src/Blocks/components/head/head.php
  blocks/init/src/Blocks/components/icon/icon.php
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php
  blocks/init/src/Blocks/components/loader/loader.php
  blocks/init/src/Blocks/components/logo/logo.php
  blocks/init/src/Blocks/components/menu/menu.php
  blocks/init/src/Blocks/components/modal/modal.php
  blocks/init/src/Blocks/components/paragraph/paragraph.php
  blocks/init/src/Blocks/components/quote/quote.php
  blocks/init/src/Blocks/components/scroll-to-top/scroll-to-top.php
  blocks/init/src/Blocks/components/search-bar/search-bar.php
  blocks/init/src/Blocks/components/share/share.php
  blocks/init/src/Blocks/components/skip-link/skip-link.php
  blocks/init/src/Blocks/components/social-links/social-links.php
  blocks/init/src/Blocks/components/video/video.php
  blocks/init/src/Blocks/custom/button/button.php
  blocks/init/src/Blocks/custom/carousel/carousel.php
  blocks/init/src/Blocks/custom/column/column.php
  blocks/init/src/Blocks/custom/columns/columns.php
  blocks/init/src/Blocks/custom/example/example.php
  blocks/init/src/Blocks/custom/featured-categories/featured-categories.php
  blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
  blocks/init/src/Blocks/custom/group/group.php
  blocks/init/src/Blocks/custom/heading/heading.php
  blocks/init/src/Blocks/custom/image/image.php
  blocks/init/src/Blocks/custom/lists/lists.php
  blocks/init/src/Blocks/custom/paragraph/paragraph.php
  blocks/init/src/Blocks/custom/quote/quote.php
  blocks/init/src/Blocks/custom/video/video.php
  blocks/init/src/Blocks/wrapper/wrapper.php
Labels: bugfix

#586 Fix for option overflow when scrollbars are enabled
  styles/override-editor.scss
Labels: bugfix

#584 Fix hamburger label conditional
  blocks/init/src/Blocks/components/hamburger/hamburger.php
Labels: bugfix, a11y

#587 ColorPaletteCustom rework
  scripts/components/color-palette-custom/color-palette-custom.js
  scripts/components/color-palette-custom/color-palette-custom.scss
  scripts/components/color-picker-component/color-picker-component.js
  scripts/components/index.js
  scripts/editor/icons/icons.js
  scripts/index.js
  styles/es-component-styles.scss
  styles/es-utility-classes.scss
Labels: improvement

#588 Inline style tags
  blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js
  blocks/init/src/Blocks/manifest.json
  schemas/globalManifest.json
  scripts/editor/get-manifest-details.js
  scripts/editor/index.js
  scripts/editor/output-css-variables.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
  scripts/index.js
Labels: improvement

#591 Text helpers fixes and tests
  scripts/helpers/text-helpers.js
  tests/unit/scripts/helpers/text-helpers.test.js
Labels: bugfix

#590 SimpleHorizontalSingleSelect
  scripts/components/index.js
  scripts/components/simple-horizontal-single-select/docs/readme.mdx
  scripts/components/simple-horizontal-single-select/docs/story.js
  scripts/components/simple-horizontal-single-select/simple-horizontal-single-select.js
  scripts/components/simple-horizontal-single-select/simple-horizontal-single-select.scss
  scripts/editor/icons/icons.js
  scripts/index.js
  styles/es-component-styles.scss
  styles/es-utility-classes.scss
Labels: improvement

#593 Improve HTML spec compliance
  blocks/init/src/Blocks/components/hamburger/hamburger.php
  blocks/init/src/Blocks/components/head/head.php
  blocks/init/src/Blocks/components/image/image.php
  blocks/init/src/Blocks/components/quote/manifest.json
Labels: bugfix, a11y

#592 Clean changelog and versions that start from 1.0.0
  setup/create-wp-project/src/commands/theme.js
  setup/create-wp-project/src/replace-version-numbers.js
Labels: improvement, setup

#594 adding fixes for yoast seo plugin analize
  scripts/plugins/yoast-seo.js
Labels: improvement

#598 A11y improvements after a11y review
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
  blocks/init/src/Blocks/components/lists/components/lists-options.js
  blocks/init/src/Blocks/components/menu/styles/horizontal/menu-horizontal-style.scss
  blocks/init/src/Blocks/components/menu/styles/vertical/menu-vertical-style.scss
  blocks/init/src/Blocks/components/video/components/video-options.js
  blocks/init/src/Blocks/components/video/video.php
Labels: improvement, bugfix, a11y

#599 Replace role="section" with role="region"
  blocks/init/src/Blocks/components/jumbotron/jumbotron.php
Labels: bugfix, a11y
