Repository infinum/eightshift-frontend-libs, pull requests merged in 2022-01, with the labels that each got.

#536 Component improvements
  blocks/init/assets/scripts/application.js
  blocks/init/src/Blocks/assets/scripts/application-blocks.js
  scripts/components/advanced-color-picker/advanced-color-picker.js
  scripts/components/advanced-color-picker/docs/story.js
  scripts/components/alignment-toolbar/alignment-toolbar.js
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
  scripts/components/color-picker-component/color-picker-component.js
  scripts/components/custom-select/custom-select.js
  scripts/components/heading-level/heading-level.js
  scripts/components/icon-toggle/icon-toggle.js
  scripts/components/link-edit-component/link-edit-component.js
  scripts/components/link-toolbar-button/link-toolbar-button.js
  scripts/components/option-picker/option-picker.js
  scripts/components/simple-vertical-single-select/simple-vertical-single-select.js
Labels: improvement

#538 Script reference improvement
  scripts/index.js
Labels: improvement

#532 Async options filtering in CustomSelect component
  scripts/components/custom-select/custom-select.js
  scripts/components/custom-select/docs/readme.mdx
  scripts/editor/fetch-wp-api.js
Labels: improvement, feature request

#539 Fix for advanced color picker
  scripts/index.js
Labels: bugfix

#544 Feature/schemas
  blocks/init/src/Blocks/components/button/manifest.json
  blocks/init/src/Blocks/custom/button/manifest.json
  blocks/init/src/Blocks/variations/button-block/manifest.json
  schemas/block.json
  schemas/component.json
  schemas/variation.json
  scripts/editor/register-blocks.js
Labels: improvement

#545 adding global setting schema
  blocks/init/src/Blocks/manifest.json
  schemas/settings.json
Labels: improvement

#549 Release/5.0.3
  .github/workflows/ci.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  __mocks__/@eightshift/frontend-libs/mocks/wrapper.js
  __mocks__/@wordpress/block-editor.js
  __mocks__/@wordpress/blocks.js
  __mocks__/@wordpress/element.js
  __mocks__/react-html-parser.js
  blocks/init/src/Blocks/components/jumbotron/components/jumbotron-toolbar.js
  blocks/init/src/Blocks/components/modal/docs/story.js
  blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/components/video/components/video-editor.js
  blocks/init/src/Blocks/components/video/components/video-options.js
  blocks/init/src/Blocks/custom/column/column-hooks.js
  blocks/init/src/Blocks/story.js
  package.json
  scripts/components/advanced-color-picker/advanced-color-picker.js
  scripts/components/advanced-color-picker/docs/story.js
  scripts/components/alignment-toolbar/alignment-toolbar.js
  scripts/components/color-picker-component/color-picker-component.js
  scripts/components/color-picker-component/docs/story.js
  scripts/components/component-use-toggle/component-use-toggle.js
  scripts/components/component-use-toggle/docs/story.js
  scripts/components/custom-select/custom-select.js
  scripts/components/custom-select/docs/story.js
  scripts/components/heading-level/heading-level.js
  scripts/components/icon-label/docs/story.js
  scripts/components/icon-toggle/docs/story.js
  scripts/components/icon-toggle/icon-toggle.js
  scripts/components/inline-notification/docs/story.js
  scripts/components/inline-notification/inline-notification.js
  scripts/components/link-edit-component/docs/story.js
  scripts/components/link-edit-component/link-edit-component.js
  scripts/components/link-toolbar-button/docs/story.js
  scripts/components/link-toolbar-button/link-toolbar-button.js
  scripts/components/matrix-align-control/docs/story.js
  scripts/components/matrix-align-control/matrix-align-control.js
  scripts/components/option-picker/docs/story.js
  scripts/components/option-picker/option-picker.js
  scripts/components/responsive/responsive.js
  scripts/components/server-side-render/docs/story.js
  scripts/components/server-side-render/server-side-render.js
  scripts/components/simple-vertical-single-select/docs/story.js
  scripts/components/simple-vertical-single-select/simple-vertical-single-select.js
  scripts/editor/fetch-wp-api.js
  scripts/editor/get-options.js
  scripts/editor/icons/icons.js
  scripts/editor/inserter.js
  scripts/editor/output-css-variables.js
  scripts/editor/paste-handler.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
  scripts/helpers/camelize.js
  scripts/helpers/check-attr.js
  scripts/helpers/text-helpers.js
  scripts/plugins/yoast-seo.js
  webpack/production.js
Labels: improvement

#540 Improve header / footer accessibility, fix #534
  blocks/init/src/Blocks/components/drawer/assets/drawer.js
  blocks/init/src/Blocks/components/drawer/drawer-style.scss
  blocks/init/src/Blocks/components/drawer/drawer.php
  blocks/init/src/Blocks/components/drawer/manifest.json
  blocks/init/src/Blocks/components/hamburger/hamburger.php
  blocks/init/src/Blocks/components/hamburger/manifest.json
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php
  blocks/init/src/Blocks/components/layout-three-columns/manifest.json
Labels: bugfix, a11y
