Repository infinum/eightshift-frontend-libs, pull requests merged in 2022-02, with the labels that each got.

#555 CustomSlider and CustomRangeSlider
  package.json
  scripts/components/custom-slider/custom-range-slider.js
  scripts/components/custom-slider/custom-slider.js
  scripts/components/custom-slider/custom-slider.scss
  scripts/components/custom-slider/docs/readme.mdx
  scripts/components/custom-slider/docs/story.js
  scripts/components/index.js
  scripts/index.js
  styles/storybook.scss
Labels: improvement, new component

#557 Custom slider fixes
  scripts/components/custom-slider/custom-range-slider.js
  scripts/components/custom-slider/custom-slider.js
  scripts/components/index.js
  styles/override-editor.scss
Labels: bugfix

#558 Accordion A11y improvements
  blocks/init/src/Blocks/components/accordion/accordion-style.scss
  blocks/init/src/Blocks/components/accordion/accordion.php
  blocks/init/src/Blocks/components/accordion/assets/accordion.js
Labels: bugfix, a11y

#559 Change color scheme to match WCAG contrast requirements
  blocks/init/src/Blocks/components/button/manifest.json
  blocks/init/src/Blocks/components/lists/manifest.json
  blocks/init/src/Blocks/components/paragraph/manifest.json
  blocks/init/src/Blocks/manifest.json
Labels: bugfix, a11y

#560 New icons and styles
  scripts/components/fancy-divider/docs/readme.mdx
  scripts/components/fancy-divider/docs/story.js
  scripts/components/fancy-divider/fancy-divider.js
  scripts/components/index.js
  scripts/editor/icons/icons.js
  scripts/index.js
  styles/override-editor.scss
Labels: improvement

#563 Fix text domains
  blocks/init/src/Blocks/components/hamburger/hamburger.php
  blocks/init/src/Blocks/components/modal/modal.php
Labels: bugfix

#562 Add skip link component
  blocks/init/src/Blocks/components/skip-link/docs/readme.mdx
  blocks/init/src/Blocks/components/skip-link/manifest.json
  blocks/init/src/Blocks/components/skip-link/skip-link-style.scss
  blocks/init/src/Blocks/components/skip-link/skip-link.php
Labels: new component, a11y

#565 Components style separation and component improvements
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.scss
  scripts/components/collapsable-component-use-toggle/docs/story.js
  scripts/components/color-picker-component/color-picker-component.scss
  scripts/components/component-use-toggle/component-use-toggle.scss
  scripts/components/custom-select/custom-select.scss
  scripts/components/fancy-divider/fancy-divider.scss
  scripts/components/help-modal/help-modal.scss
  scripts/components/icon-toggle/icon-toggle.scss
  scripts/components/inline-notification/inline-notification.scss
  scripts/components/link-edit-component/link-edit-component.js
  scripts/components/link-edit-component/link-edit-component.scss
  scripts/components/responsive/responsive.scss
  scripts/components/server-side-render/server-side-render.scss
  scripts/components/simple-vertical-single-select/simple-vertical-single-select.scss
  styles/es-component-styles.scss
  styles/es-keyframes.scss
  styles/es-utility-classes.scss
  styles/override-editor.scss
Labels: improvement, scss

#556 Fix warnings on hsl function
  styles/override-editor.scss
Labels: improvement

#566 Minor style fixes
  styles/es-component-styles.scss
  styles/es-utility-classes.scss
Labels: bugfix

#564 Improvements for small viewports
  blocks/init/src/Blocks/components/header/header-style.scss
  blocks/init/src/Blocks/components/heading/heading-style.scss
  blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns-style.scss
  blocks/init/src/Blocks/components/lists/lists-style.scss
  blocks/init/src/Blocks/components/menu/styles/horizontal/menu-horizontal-style.scss
  blocks/init/src/Blocks/components/menu/styles/vertical/menu-vertical-style.scss
  blocks/init/src/Blocks/components/paragraph/paragraph-style.scss
  blocks/init/src/Blocks/custom/featured-posts/components/featured-posts-options.js
  blocks/init/src/Blocks/custom/featured-posts/manifest.json
Labels: a11y

#568 Custom select custom component wrappers
  scripts/components/custom-select/custom-select.js
  scripts/components/custom-select/docs/story.js
  scripts/components/index.js
  scripts/index.js
Labels: improvement

#569 Component and icon updates backport 2
  blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js
  blocks/init/src/Blocks/components/video/components/video-options.js
  blocks/init/src/Blocks/story.js
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
  scripts/components/custom-select/custom-select.js
  scripts/editor/get-options.js
  scripts/editor/icons/icons.js
  scripts/editor/output-css-variables.js
  scripts/editor/paste-handler.js
  scripts/editor/props.js
  scripts/editor/register-blocks.js
  scripts/helpers/camelize.js
  scripts/helpers/check-attr.js
  scripts/plugins/yoast-seo.js
  webpack/production.js
Labels: improvement

#572 Carousel A11y improvements
  blocks/init/src/Blocks/custom/carousel/assets/carousel-slider.js
  blocks/init/src/Blocks/custom/carousel/carousel.php
Labels: a11y
