Repository infinum/eightshift-frontend-libs, pull requests merged in 2022-04, with the labels that each got.

#601 Feature/icons additions and updates
  scripts/editor/icons/icons.js
Labels: improvement

#602 Fix WP SCRIPT_DEBUG strict mode quirk with ColorPickerComponent
  scripts/components/color-picker-component/color-picker-component.js
Labels: bugfix

#603 New forms block icons
  scripts/editor/icons/icons.js
Labels: improvement

#605 adding option to remove wrapper
  blocks/init/src/Blocks/manifest.json
  schemas/globalManifest.json
  scripts/editor/registration.js
  scripts/editor/store.js
Labels: improvement

#608 Component additions and updates
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
  scripts/components/collapsable/collapsable.js
  scripts/components/collapsable/collapsable.scss
  scripts/components/color-palette-custom/color-palette-custom.js
  scripts/components/compact-responsive/compact-responsive.js
  scripts/components/compact-responsive/compact-responsive.scss
  scripts/components/compact-responsive/docs/readme.mdx
  scripts/components/compact-responsive/docs/story.js
  scripts/components/icon-toggle/docs/readme.mdx
  scripts/components/icon-toggle/docs/story.js
  scripts/components/icon-toggle/icon-toggle.js
  scripts/components/icon-toggle/icon-toggle.scss
  scripts/components/index.js
  scripts/components/link-edit-component/link-edit-component.js
  scripts/editor/icons/icons.js
  scripts/index.js
  styles/es-component-styles.scss
  styles/es-keyframes.scss
  styles/es-utility-classes.scss
  styles/override-editor.scss
Labels: improvement, bugfix

#600 updating css variables
  blocks/init/assets/styles/parts/_core.scss
  blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js
  blocks/init/src/Blocks/manifest.json
  blocks/init/src/Blocks/wrapper/wrapper-hooks.js
  schemas/globalManifest.json
  scripts/editor/actions.js
  scripts/editor/attributes.js
  scripts/editor/colors.js
  scripts/editor/css-variables.js
  scripts/editor/editor.js
  scripts/editor/fetch.js
  scripts/editor/get-manifest-details.js
  scripts/editor/hooks.js
  scripts/editor/index.js
  scripts/editor/inserter.js
  scripts/editor/options.js
  scripts/editor/override-inner-block-attributes.js
  scripts/editor/props.js
  scripts/editor/registration.js
  scripts/editor/selectors.js
  scripts/editor/store.js
  scripts/editor/utility.js
  scripts/helpers/check-attr.js
  scripts/helpers/index.js
  scripts/helpers/selector.js
  scripts/index.js
  scripts/plugins/yoast-seo.js
  tests/helpers/blocks.js
  tests/setup-global.js
  tests/unit/blocks/block-registration.test.js
  tests/unit/scripts/editor/hex-to-rgb.test.js
  tests/unit/scripts/editor/option-colors.test.js
  tests/unit/scripts/editor/ucfirst.test.js
  tests/unit/scripts/helpers/check-attr.test.js
Labels: improvement

#610 Fix Gradient Picker component
  scripts/components/advanced-color-picker/advanced-color-picker.js
Labels: bugfix
