Repository infinum/eightshift-frontend-libs, pull requests merged in 2022-06, with the labels that each got.

#624 Rem base size
  blocks/init/assets/styles/parts/utils/_shared-variables.scss
  blocks/init/src/Blocks/assets/styles/application-blocks-frontend.scss
  blocks/init/src/Blocks/assets/styles/editor/_editor.scss
  blocks/init/src/Blocks/assets/styles/frontend/_frontend.scss
  blocks/init/src/Blocks/manifest.json
  schemas/globalManifest.json
  scripts/components/server-side-render/server-side-render.js
  scripts/editor/css-variables.js
  scripts/editor/store.js
Labels: improvement, feature request

#629 Webpack 5 - seperate Normalize import from main index.scss
  blocks/init/src/Blocks/assets/styles/application-blocks-editor.scss
  blocks/init/src/Blocks/assets/styles/application-blocks-frontend.scss
  blocks/init/src/Blocks/assets/styles/application-blocks.scss
  styles/index.scss
Labels: bugfix

#630 adding variations to store
  scripts/editor/registration.js
  scripts/editor/store.js
Labels: improvement, feature request

#633 Rem base size
  blocks/init/assets/styles/parts/_core.scss
  blocks/init/assets/styles/parts/utils/_shared-variables.scss
  blocks/init/src/Blocks/assets/styles/editor/_editor.scss
  blocks/init/src/Blocks/assets/styles/frontend/_frontend.scss
  styles/scss/functions/_all.scss
  styles/scss/functions/_global-config.scss
  webpack/base.js
  webpack/helpers.js
Labels: bugfix

#637 Remove unnecessary escaping in carousel template file
  blocks/init/src/Blocks/custom/carousel/carousel.php
Labels: improvement, bugfix

#639 SASS map output fix if comma in value
  webpack/helpers.js
Labels: bugfix

#638 Stylelint updates and fixes
  blocks/init/assets/styles/parts/_core.scss
  blocks/init/assets/styles/parts/utils/_shared-variables.scss
  blocks/init/src/Blocks/components/button/button-frontend.scss
  blocks/init/src/Blocks/components/hamburger/hamburger-style.scss
  blocks/init/src/Blocks/components/layout/layout-style.scss
  blocks/init/src/Blocks/components/loader/loader-style.scss
  blocks/init/src/Blocks/components/menu/styles/horizontal/menu-horizontal-style.scss
  blocks/init/src/Blocks/components/menu/styles/vertical/menu-vertical-style.scss
  blocks/init/src/Blocks/components/modal/modal-style.scss
  blocks/init/src/Blocks/components/quote/quote-style.scss
  blocks/init/src/Blocks/components/share/share-style.scss
  blocks/init/src/Blocks/custom/button/button-editor.scss
  blocks/init/src/Blocks/custom/button/button-frontend.scss
  blocks/init/src/Blocks/custom/example/example-editor.scss
  blocks/init/src/Blocks/custom/example/example-style.scss
  blocks/init/src/Blocks/wrapper/wrapper-editor.scss
  blocks/init/src/Blocks/wrapper/wrapper-frontend.scss
  blocks/init/src/Blocks/wrapper/wrapper-style.scss
  linters/stylelint.config.js
  scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.scss
  scripts/components/compact-responsive/compact-responsive.scss
  scripts/components/custom-slider/custom-slider.scss
  styles/scss/_normalize.scss
  styles/scss/functions/_global-config.scss
  styles/scss/functions/_global-settings.scss
  styles/scss/functions/_map-get-deep.scss
  styles/scss/functions/_map-get-strict.scss
  styles/scss/functions/_map-reverse.scss
  styles/scss/functions/_strip-unit.scss
  styles/scss/mixins/_column-offset-modifiers.scss
  styles/scss/mixins/_flex-column-width-modifiers.scss
  styles/scss/mixins/_flex-grid-width-modifiers.scss
  styles/scss/mixins/_flex.scss
  styles/scss/mixins/_font-smoothing.scss
  styles/scss/mixins/_grid-offset-modifiers.scss
  styles/scss/mixins/_inline-font-colors.scss
  styles/scss/mixins/_link-modifiers.scss
  styles/scss/mixins/_link.scss
  styles/scss/mixins/_modifiers-deep.scss
  styles/scss/mixins/_modifiers-range.scss
  styles/scss/mixins/_modifiers.scss
  styles/scss/mixins/_responsive-modifiers.scss
  styles/scss/mixins/_responsive-selectors-visibility.scss
  styles/scss/mixins/_responsive-selectors.scss
  styles/scss/mixins/_responsive.scss
  styles/scss/mixins/_underline-text.scss
  styles/scss/placeholders/_link.scss
Labels: improvement
